issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-demo/guardcraft-server:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-demo/guardcraft-server/.github/workflows/digestabot.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
